algoritmo "exercicio10"
var
   dia: inteiro
inicio
   escreva("Digite um numero de 1 a 7: ")
   leia(dia)

   escolha dia
      caso 1
         escreval("Domingo")
      caso 2
         escreval("Segunda-feira")
      caso 3
         escreval("Terca-feira")
      caso 4
         escreval("Quarta-feira")
      caso 5
         escreval("Quinta-feira")
      caso 6
         escreval("Sexta-feira")
      caso 7
         escreval("Sabado")
      outrocaso
         escreval("Dia da semana invalido")
   fimescolha
fimalgoritmo
